CREATE TABLE `oferta` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `version` int(11) NOT NULL,
  `titulo` varchar(255) NOT NULL,
  `descripcion` varchar(255) NOT NULL,
  `dotacion` decimal(19,2) NOT NULL,
  `duracion` decimal(19,2) NOT NULL,
  `horas` int(3) NOT NULL,
  `fechaInicio` date NOT NULL,
  `fechaFin` date NOT NULL,
  `esCurricular` tinyint(1) NOT NULL,
  `pais` varchar(255) NOT NULL,
  `provincia` varchar(255),
  `localidad` varchar(255),
  `empresa` varchar(255) NOT NULL,
  `cifEmp` varchar(255) NOT NULL,
  `telefonoEmp` varchar(255) NOT NULL,
  `emailEmp` varchar(255) NOT NULL,
  `tutorEmp` varchar(255) NOT NULL,
  `enEvaluacion` tinyint(1) NOT NULL,
  `docuCerrada` tinyint(1) NOT NULL,
  `evaluada` tinyint(1) NOT NULL,
  `preacta` tinyint(1) NOT NULL,
  `actaFirmada` tinyint(1) NOT NULL,
  `expedienteCerrado` tinyint(1) NOT NULL,
  `alumnoAsignado_id` int(11) NOT NULL,
  `tutorAsignado_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`alumnoAsignado_id`) REFERENCES `actor` (`id`),
  FOREIGN KEY (`tutorAsignado_id`) REFERENCES `actor` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;